# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [cann, Hanna]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username mouse3687
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., asana-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username mouse3687
otechie: # Replace with a single Otechie username mouse3687
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Masterclass.com','https://vodoo.io','https://azure.com','https://fema.gov','https://Verizon.com','https://www.theguardian.com/us-news/2020/may/21/open-skies-us-russia-arms-treaty-trump-pulls-out?CMP=Share_iOSApp_Other','https://chime.com','https://vinelink.com','https://marchofdimes.org', 'https://Zacks.com']
